baseurl: https://wxhyihuan.netlify.app/
languageCode: en-us
title: Wxh yihuan
theme: "hugo-ivy"
googleAnalytics: false
disqusShortname: true
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: â†©
paginate: 4

permalinks:
  note: /note/:year/:month/:day/:slug/
  post: /post/:year/:month/:day/:slug/

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Categories"
      url: "/categories/"
      weight: 3
    - name: "Tags"
      url: "/tags/"
      weight: 4
    - name: "Subscribe"
      url: "/index.xml"
    - name: "Vitae"
      url: "/vitae/"
      weight: 2

params:
  description: "A Hugo theme ported from the static site generator Ivy."
  footer: "&copy; [Wxhyihuan](https://wxhyihuan.github.io/) 2017 | [Github](https://github.com/wxhyihuan) | [Twitter](https://twitter.com/wxhyihuan)"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex", "python", "sql", "Markdown", "bash"]
  highlightjsTheme: "rainbow"
  highlightjsVersion: "10.5.0"
  
  MathJaxCDN: "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion: "2.7.5"


markup:
  goldmark:
    renderer:
      unsafe: true

